package in.ecomexpress.sathi.repo.local.db.model;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Generated by Dipendra on 08-11-2017 - 01:02 PM
 */

@Entity
public class User {

    @PrimaryKey(autoGenerate = true)
    private int id;
    private int userId;
    private String userName;
    private long userContact;
    private String userLocation;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public long getUserContact() {
        return userContact;
    }

    public void setUserContact(long userContact) {
        this.userContact = userContact;
    }

    public String getUserLocation() {
        return userLocation;
    }

    public void setUserLocation(String userLocation) {
        this.userLocation = userLocation;
    }
}
