package in.ecomexpress.sathi.di;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import javax.inject.Qualifier;

/**
 * Generated by Dipendra on 08/11/17 - 12:10 PM
 */

@Qualifier
@Documented
@Retention(RetentionPolicy.RUNTIME)
public @interface DatabaseInfo {
    String value() default "";
}
